### PR TITLE
Move "Dark Mode" Setting from About Tab to Config Tab 

### PR DESCRIPTION
**Pull request by ahoehne**
o7
i've moved the Dark Mode setting to the config tab, it was previously on the about tab
I also adjusted window size and some of the config setting positions to fit properly without scrolling

### CODE REVIEW

**Review by Riftr — APPROVED** [review]
Look good

**Review by Riftr — CHANGES_REQUESTED** [review]
This one also looks good however I'm not sure about the change to set the config screen as the default. While I understand why we might want to do this in order to prompt people to set things up correctly, once it's set up it's then another click every time you start the app.

**Review by Riftr — APPROVED** [review]
Makes sense.

**Review by Riftr — APPROVED** [review]
Looks good

**Comment by Riftr** [comment]
I'm going to go ahead and merge this then revert the default tab change.

**Comment by ahoehne** [comment]
Ah sorry, was on tour for some time and didn't noticed the answer.
Modifying the default tab was unintended/unnoticed, thanks alot for reverting that.

**Pull request merged**
